# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
- develop
- feature/*

pool:
  vmImage: 'ubuntu-16.04' 

variables:
  dockerId: ristl17  
  imageName: 'ticketing:$(build.buildNumber)'

steps:
- script: |
    docker build -t $(dockerId)/$(imageName) .